### PR TITLE
NOPS-753 - ES consul plugin for 2.4.0

### PR DESCRIPTION
**Pull request by ashilokhvostov**
Change `pom.xml` to creating deb package ES consul plugin 2.4.0

### CODE REVIEW

**Comment by ashilokhvostov** [comment]
- vagrant up
- vagrant ssh
- cd elasticsearch-consul-discovery/
- mvn package

> .....
> [INFO] Creating debian package: /vagrant/elasticsearch-consul-discovery-2.4.0.deb
> [INFO] Building data
> [INFO] file:./usr/share/elasticsearch/plugins/consul-discovery/elasticsearch-consul-discovery-2.4.0.jar size:19187 mode:420 linkname: username:root userid:0 groupname:root groupid:0 modtime:Thu Sep 22 06:01:22 UTC 2016 md5: 8bf1a4372d9b60b08b1448cfac2da6e9
> [INFO] file:./usr/share/elasticsearch/plugins/consul-discovery/gson-2.3.1.jar size:210856 mode:420 linkname: username:root userid:0 groupname:root groupid:0 modtime:Thu Sep 22 06:01:22 UTC 2016 md5: e16b1b8fca0980263f764f633ec91dd6
> [INFO] file:./usr/share/elasticsearch/plugins/consul-discovery/plugin-descriptor.properties size:2620 mode:420 linkname: username:root userid:0 groupname:root groupid:0 modtime:Thu Sep 22 06:01:23 UTC 2016 md5: 25204bfd357f914009e51602d4c14751
> [INFO] Total size: 232663
> [INFO] Building conffiles
> [INFO] Building control
> [INFO] Skipping 'conffiles' generation. No entries provided.
> [INFO] Creating changes file: /vagrant/target/elasticsearch-consul-discovery_2.4.0_all.changes
> [INFO] Attaching created debian package /vagrant/elasticsearch-consul-discovery-2.4.0.deb
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 01:36 min
> [INFO] Finished at: 2016-09-22T06:01:23+00:00
> [INFO] Final Memory: 28M/82M
> [INFO] ------------------------------------------------------------------------

**Comment by mkostrikin** [comment]
💾

**Comment by mkostrikin** [comment]
@nokk please review

**Comment by nokk** [comment]
Very cool. 👍  Just of curiousity, why dont we use https://github.com/Tradeshift/tradeshift-debian-packages ?

**Comment by ashilokhvostov** [comment]
We need build the code and then we make a package. In `tradeshift-debian-packages` we not build the code.

**Pull request merged**
